services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: boot
      MONGO_INITDB_DATABASE: product_microservice
    ports:
      - 27017:27017
    volumes:
      - db:/data/db

volumes:
  db: